export const data = [
  {
    id: "7301663193485480056a",
    name: "О чем молчит кандидат: как проверить его опыт",
    local_time_string: "Мск",
    max_pers: 39,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description: "",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей",
    event_rb_type: "manp][Менеджерские программы",
    beexpert: 0,
    is_la: 0,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-check-circle][Ответственность;fa-handshake][Инновации;fa-user][Клиент",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "Вне учебного класса",
    class: "Вебинар.ру",
    type: "webinar",
    start_date: "2024-02-13T10:00:00+00:00",
    finish_date: "2024-02-15T13:00:00+00:00",
    is_passed: 0,
    company: "Дынина Ольга Сергеевна",
    Mandatorys: "0",
  },
  {
    id: "7311573874567419695s",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 991,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "На рабочих местах",
    type: "webinar",
    start_date: "2024-02-02T08:50:00+00:00",
    finish_date: "2024-02-02T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311573874567419695s",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 991,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "На рабочих местах",
    type: "webinar",
    start_date: "2024-02-02T08:50:00+00:00",
    finish_date: "2024-02-02T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311573874567419695s",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 991,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "На рабочих местах",
    type: "webinar",
    start_date: "2024-02-02T08:50:00+00:00",
    finish_date: "2024-02-02T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311573874567419695s",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 991,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "На рабочих местах",
    type: "webinar",
    start_date: "2024-02-02T08:50:00+00:00",
    finish_date: "2024-02-02T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311573874567419695s",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 991,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "На рабочих местах",
    type: "webinar",
    start_date: "2024-02-02T08:50:00+00:00",
    finish_date: "2024-02-02T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311573874567419695s",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 991,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "На рабочих местах",
    type: "webinar",
    start_date: "2024-02-02T08:50:00+00:00",
    finish_date: "2024-02-02T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311573874567419695s",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 991,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "На рабочих местах",
    type: "webinar",
    start_date: "2024-02-02T08:50:00+00:00",
    finish_date: "2024-02-02T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311573874567419695s",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 991,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "На рабочих местах",
    type: "webinar",
    start_date: "2024-02-02T08:50:00+00:00",
    finish_date: "2024-02-02T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311573874567419695s",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 991,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "На рабочих местах",
    type: "webinar",
    start_date: "2024-02-02T08:50:00+00:00",
    finish_date: "2024-02-02T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311573874567419695s",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 991,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "На рабочих местах",
    type: "webinar",
    start_date: "2024-02-02T08:50:00+00:00",
    finish_date: "2024-02-02T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311573874567419695s",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 991,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "На рабочих местах",
    type: "webinar",
    start_date: "2024-01-31T08:50:00+00:00",
    finish_date: "2024-02-03T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869979412d",
    name: "Лидерская пятница. Тема уточняется",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-02-16T08:50:00+00:00",
    finish_date: "2024-02-16T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869979412deewr3",
    name: "Starting",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-01-16T08:50:00+00:00",
    finish_date: "2024-01-16T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869979412dadd",
    name: "some event",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-01-16T08:50:00+00:00",
    finish_date: "2024-01-17T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869979412dadd",
    name: "some event",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-01-16T08:50:00+00:00",
    finish_date: "2024-01-18T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869979412dadd",
    name: "some event",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-01-17T08:50:00+00:00",
    finish_date: "2024-01-18T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869979412dadd",
    name: "some event",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-01-12T08:50:00+00:00",
    finish_date: "2024-01-12T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869979412dadd",
    name: "some event",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-01-09T08:50:00+00:00",
    finish_date: "2024-01-12T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869979412dadd",
    name: "some event",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-01-01T08:50:00+00:00",
    finish_date: "2024-01-01T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869979412dadd",
    name: "some event",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-01-04T08:50:00+00:00",
    finish_date: "2024-01-04T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869sdfs979412dadd",
    name: "some event",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2025-03-04T08:50:00+00:00",
    finish_date: "2025-03-04T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869sdfs979412d213weadd",
    name: "some event",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-01-23T08:50:00+00:00",
    finish_date: "2024-01-25T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869sdfs979412d2ss13weadd",
    name: "some event",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-01-17T08:50:00+00:00",
    finish_date: "2024-01-19T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
  {
    id: "7311576497869sdfs979412d2ss13weadd",
    name: "long event",
    local_time_string: "мск",
    max_pers: 992,
    is_open: 1,
    registred: 0,
    in_wlist: 0,
    price: "",
    is_single_person_price: 0,
    description:
      "<p>Приглашаем вас на встречу в рамках проекта &quot;Лидерские пятницы &quot;.</p><p>Детали подключения будут направлены после регистрации.</p>",
    calendar_group: 0,
    type_no_access: "",
    for_type: "boss][Для руководителей;spec][Для специалистов",
    event_rb_type:
      "manp][Менеджерские программы;tle][Тренинги личной эффективности",
    beexpert: 0,
    is_la: 1,
    is_devops: 0,
    starting: 0,
    type_val:
      "fa-heart][Вовлеченность;fa-lightbulb][Командный br дух;fa-handshake][Инновации;fa-check-circle][Ответственность",
    hub: "all_locations][Все города",
    type_detailed: "type_webinar][Вебинар",
    place: "На рабочих местах",
    class: "на рабочих местах",
    type: "webinar",
    start_date: "2024-01-12T08:50:00+00:00",
    finish_date: "2024-01-19T10:00:00+00:00",
    is_passed: 0,
    company: "ПРОВАЙДЕР",
    Mandatorys: "0",
  },
];
